# Name of website
favicon: assets/image/IMG_2802.jpeg 
baseurl: '/Chris-Gonz'
title: Christian Gonzalez

author: Chris

logo: assets/image/IMG_2802.jpeg
round-logo: true
description: CVG
show_downloads: true
theme:  jekyll-theme-minimal

