# Name of website
favicon: /assets/image/portBust.jpg
baseurl: '/Chris-Gonz'
title: Christian Gonzalez

author: Chris

logo: assets/image/portBust.jpg
round-logo: true
#description: [ADD SMALL DESCRIPTION]
show_downloads: true
theme:  jekyll-theme-minimal

