# Name of website
# favicon: ''
baseurl: '/Chris-Gonz'
title: Christian Gonzalez

author: Chris

logo: assets/image/port_bust.jpg
round-logo: true
#description: [ADD SMALL DESCRIPTION]
show_downloads: false
theme:  jekyll-theme-minimal

