# Name of website
# favicon: assets/image/sun.svg 
baseurl: ''
title: Christian Gonzalez

author: Chris

logo: /assets/image/round_port.svg
round-logo: true
description: CVG
show_downloads: true
theme:  jekyll-theme-minimal

