# Name of website
favicon: assets/image/sun.svg 
baseurl: '/chris-gonz.github.io'
title: Christian Gonzalez

author: Chris

logo: assets/image/sun.svg
round-logo: true
description: CVG
show_downloads: true
theme:  jekyll-theme-minimal

